import express from "express";
import cors from "cors";
import router from "./routes/auth.routes.js";
import globalErrorHandler from "./middlewares/error.middleware.js";
const app = express();
app.use(cors());
app.use(express.json());
app.use("/api/auth", router);
app.use(globalErrorHandler);
export default app;
